### PR TITLE
media player captions styling override

### PR DESCRIPTION
**Pull request by moloko**
to save me having to do this on every project that uses .vtt captions...!

### CODE REVIEW

**Review by kirsty-hames — APPROVED** [review]

**Comment by kirsty-hames** [comment]
@moloko, the caption background overlapping issue will most likely be a global issue as the font size and line height is inherited from .mejs-captions-layer in mep.less.

Should line 21 onwards get added to the plugin less?

**Comment by moloko** [comment]
> Should line 21 onwards get added to the plugin less?

Almost certainly, I was just being lazy adding it here rather than getting it fixed open source... happy to change it if you want though.

**Comment by kirsty-hames** [comment]
No worries, either is fine by me thanks :)

**Comment by moloko** [comment]
OK I've actually added the 'hide the caption language selector that gets shown when you click the 'cc' button' stuff to https://github.com/adaptlearning/adapt-contrib-media/pull/188 - if that gets merged OK I'll remove that from this PR

**Pull request merged**
